# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: remote_logging/logging.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'remote_logging/logging.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cremote_logging/logging.proto\x12\x0eremote_logging\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xe9\x01\n\x08LogEntry\x12-\n\ttimestamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\r\n\x05level\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\x12\x0e\n\x06source\x18\x04 \x01(\t\x12\x36\n\x07\x63ontext\x18\x05 \x03(\x0b\x32%.remote_logging.LogEntry.ContextEntry\x1a\x46\n\x0c\x43ontextEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12%\n\x05value\x18\x02 \x01(\x0b\x32\x16.google.protobuf.Value:\x02\x38\x01\"H\n\nLogSummary\x12\x18\n\x10\x65ntries_received\x18\x01 \x01(\x04\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x0f\n\x07message\x18\x03 \x01(\t2U\n\x0eLoggingService\x12\x43\n\tStreamLog\x12\x18.remote_logging.LogEntry\x1a\x1a.remote_logging.LogSummary(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'remote_logging.logging_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOGENTRY_CONTEXTENTRY']._loaded_options = None
  _globals['_LOGENTRY_CONTEXTENTRY']._serialized_options = b'8\001'
  _globals['_LOGENTRY']._serialized_start=112
  _globals['_LOGENTRY']._serialized_end=345
  _globals['_LOGENTRY_CONTEXTENTRY']._serialized_start=275
  _globals['_LOGENTRY_CONTEXTENTRY']._serialized_end=345
  _globals['_LOGSUMMARY']._serialized_start=347
  _globals['_LOGSUMMARY']._serialized_end=419
  _globals['_LOGGINGSERVICE']._serialized_start=421
  _globals['_LOGGINGSERVICE']._serialized_end=506
# @@protoc_insertion_point(module_scope)
