# config.yaml
api:
  base_url: "http://localhost:8080"
  auth:
    email: "agent@example.com"
    password: "password123"

cfr_training:
  num_iterations: 100000
  save_interval: 5000
  pruning_enabled: true
  pruning_threshold: 1.0e-6

cfr_plus_params:
  weighted_averaging_enabled: true
  averaging_delay: 100 # Start weighted averaging after 100 iterations (weight = max(0, t-d))

agent_params:
  memory_level: 1 # Use Event-Triggered Decay
  time_decay_turns: 3 # Only relevant if memory_level were 2

cambia_rules:
  allowDrawFromDiscardPile: false
  allowReplaceAbilities: false
  snapRace: false
  penaltyDrawCount: 2
  use_jokers: 2
  cards_per_player: 4
  initial_view_count: 2
  cambia_allowed_round: 0
  allowOpponentSnapping: false

persistence:
  agent_data_save_path: "cambia_cfr_agent_level1.joblib"

logging:
  log_level: "DEBUG"
  log_dir: "logs" 
  log_file_prefix: "cambia"